views/order/routes.py
#!/usr/bin/python3
"""Defines all the routes for the order view"""

from flask import Blueprint, render_template, request, flash, url_for, redirect, jsonify

# Threading imports
import threading
import queue
import requests
import time

# models imports
from models.menu_items import MenuItem
from models.orders import Order
from models.accounts_models.accounts import CreditSaleTransaction
from models.customers import Customer
from models.purchases import StockItems

# python imports
from datetime import datetime
import uuid
import os

# sqlalchemy imports
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, scoped_session
from sqlalchemy import String, Column, Integer
from sqlalchemy.orm import relationship


# base_model imports
from models.base_model import BaseModel, Base, time
from models import storage

from models.categories import Category
from models.orders import Order

# engine imports
from engine.db_storage import classes, DBStorage

# define the order_views template
order_views = Blueprint('order_views', __name__,
                            template_folder='templates',
                            static_folder='static',
                            url_prefix='/order')

@order_views.route('/all-orders', strict_slashes=False)
def get_all_orders():
    """returns all the orders in the system"""
    try:
        all_orders = storage.get_all_orders()
        # Retrieving sales invoices
        invoices = storage.get_all_objects(CreditSaleTransaction)
        # Replacing id property with customer name
        for invoice in invoices:
            invoice.customer_name = storage.get_object_by_id(Customer, invoice.customer_id).customer_name

        number_of_orders = len(all_orders)

        return render_template('order.html', all_orders=all_orders,
                                number_of_orders=number_of_orders,
                                invoices=invoices,
                                number_of_invoices=len(invoices))
    except Exception as e:
        storage.rollback()
        storage.close()
        return render_template('order.html',)
    
@order_views.route('/counter-order', methods=['GET','POST'], strict_slashes=False)
def make_counter_order():
    if request.method == 'POST':
        # Process order data
        data = request.get_json()

        # Store the order in the db
        order_number = storage.get_unique_number("orders").number

        order_details = {"order_number": order_number, 
                        "customer": data["customer"],
                        "waiter": data["waiter"],
                        "table": data["table"],
                        "counter": data["counter"],
                        "tender": data["tender"],
                        "total": data["total"],
                        "isPaid": "False",
                        }

        # Increment the order number and save to the db
        new_number = order_number + 1
        storage.update_order_number(new_number)

        # If tender type is CASH save to the db
        if data["tender"] == "CASH":
            order_obj = Order(**order_details)
            storage.new(order_obj)
            storage.save()

            # Call the function that saves the order items to the db pass it the data object and order number
            save_order_items(data, order_number)

            # respond with a list of order number and the tender type
            response = [order_details["order_number"], "CASH"]
            return jsonify(response)
        
        else: #data["tender"] == "MPESA":
            q = queue.Queue()
            phone_number = data["customer"]

            # Create a thread
            mpesa_transaction_check = threading.Thread(target=process_mpesa_payment, args=(q, phone_number,))
            
            # Start the thread
            mpesa_transaction_check.start()

            #wait for the response
            mpesa_check_response = q.get()

            if mpesa_check_response == "Success":
                #response = "Transaction for number {} of amount {} found".format(data["customer"], data["total"])
                
                order_obj = Order(**order_details)
                storage.new(order_obj)
                storage.save()
                # Call the function that saves the order items to the db and pass it the data object and order number
                save_order_items(data, order_number)

                # respond with a list of order number and the tender type
                response = [order_details["order_number"], "MPESA"]
                return jsonify(response)

            else:
                return "Failed"
    
    else:
        # get all the tables
        all_tables = storage.get_all_tables()
        number_of_tables = len(all_tables)
        all_waiters = storage.get_all_waiters()
        number_of_waiters = len(all_waiters)

        all_tender_types = storage.get_tender_types()
        number_of_tender_types = len(all_tender_types)

        all_items = storage.get_menu_item()

        return render_template('make_counter_order.html', all_items=all_items,
                all_waiters=all_waiters,
                number_of_waiters=number_of_waiters,
                all_tables=all_tables,
                number_of_tables=number_of_tables,
                all_tender_types=all_tender_types,
                number_of_tender_types=number_of_tender_types
                )

def process_mpesa_payment(q, number):
    """ Processes the MPESA by checking if the combination of number, and total amount is in the mpesa transactions db table
    """
    # if the transaction is in the db respond with a success else failed
    ###
    ###
    import time
    # Sleep for 5 seconds
    time.sleep(5)
    
    # Put the response in the queue
    q.put("Success")

def save_order_items(data, order_number):
    """ Saves the order items to the database, takes thwo params: data that contains 
    the details of the items. order_number: the order number related to the items
    """
    item_names = data["items"]
    quantities = data["quantities"]
    amounts = data["amounts"]

    for item in item_names:
        quantity = quantities[item_names.index(item)]
        amount = amounts[item_names.index(item)]

        # Create an instance of an order item
        storage.create_order_item_inst(order_number, item, quantity, amount)


@order_views.route('/inv_item_details', methods=['GET','POST'], strict_slashes=False)
def get_invoice_items():
    if request.method == 'POST':
        invoice_number = request.get_json()
        try:
            invoice = storage.get_invoice_by_invoice_number(invoice_number["invNumber"])
            invoice_items = [
                {"item_name": storage.get_object_by_id(StockItems, item.stock_item_id).item_name, "quantity": item.quantity, "amount": item.amount}
                for item in invoice.stock_items
            ]
            return jsonify(invoice_items), 200
        except Exception as e:
            return jsonify({"error": "Could not retrieve invoice details"}), 500


@order_views.route('/inv_status', methods=['GET','POST'], strict_slashes=False)
def set_invoice_payment_status():
    if request.method == 'POST':
        invoice_number = request.get_json()
        try:
            storage.reload()
            invoice = storage.get_invoice_by_invoice_number(invoice_number["invNumber"])
            if not invoice.isPaid:
                invoice.isPaid = True   
                storage.new_modified(invoice)
                storage.save()
            return jsonify({"status": "isPaid"}), 200
        except Exception as e:
            return jsonify({"error": "Invoice status update failed!"}), 500
        finally:
            storage.close()


@order_views.route('/new_customer', methods=['GET', 'POST'], strict_slashes=False)
def new_customer():
    if request.method == 'POST':
        data = request.get_json()
        
        try:
            storage.reload()
            #check if customer name exists if not save the new supplier and return new customer name
            customer = storage.get_customer_by_name(data["new_customer_name"])
            if customer:
                return jsonify({"error":"Customer name already exists...!"}), 500
            else:
                new_customer = {
                    "customer_name": data["new_customer_name"],
                    "contact": data["contact"],
                    "balance": 0    #Force zero starting balance
                }
                new_customer_obj = Customer(**new_customer)
                storage.new_modified(new_customer_obj)
                return jsonify({"customer": data["new_customer_name"]}), 200
        
        except Exception as e:
            print(e)
            storage.rollback()
            return jsonify({"error": str(e)}), 500
        finally:
            storage.save()
            storage.close()

views/order/templates/make_counter_order.html
{% extends "base.html" %}

{% block content %}

<div class="pt-2">
	<div class="container py-2">
		<h2 class="text-center">New Order</h2>
	</div>
	<div class="container-fluid py-2">
		<div class="row justify-content-center py-3">
			<div class="col-md-6 text-center">
				<form class="row g-3" id="counter_header_form">
					<div class="col-md-6">
                                                <label for="counter-number" class="form-label">Counter No</label>
                                                <input type="text" class="form-control" id="counter-number" value="Billing Counter">
                                        </div>
					<div class="col-md-6">
    						<label for="table-name" class="form-label">Table</label>
    						<select class="form-select" name="table" id="table-name">
							{% for table in all_tables %}
								<option>{{ table.table_name }}</option>
							{% endfor %}
						</select>
  					</div>
					<div class="col-md-6">
                                                <label for="tender-type" class="form-label">Tender Type</label>
						<select class="form-select" name="tender-type" id="tender-type">
							{% for i in range(0, number_of_tender_types) %}
								<option>{{ all_tender_types[i] }}</option>
							{% endfor %}
						</select>
                                        </div>
					<div class="col-md-6">
                                                <label for="waiter-name" class="form-label">Waiter</label>
                                                <select class="form-select" name="table" id="waiter-name">
							{% for waiter in all_waiters %}
								<option>{{ waiter.first_name }}</option>
							{% endfor %}
						</select>
                                        </div>
				</form>

				<div class="container mt-4">
					<div class="text-start">
						<h4 class="fw-light">Menu Items</h4>
					</div>
				</div>
	
				<form class="row g-3" id="item_search_form">
					<div class="col-md-4">
						<input class="form-control" type="search" placeholder="Search" id="item-search"
						aria-label="Search">
					</div>
					<div class="col-md-4 text-start">
						<button class="btn btn-outline-success" type="submit">Search</button>
                                        </div>
					<div class="col-md-4 text-end">
                                                <button class="btn btn-primary" type="submit" id="btnCheckout">Checkout</button>
                                        </div>
				</form>

				<div class=" row g-3 my-3 form-check" id="item_check_list">
					<div class="col">
						<table class="table table-dark">
							<thead>
								<tr>
									<th scope="col"></th>
									<th scope="col">Select</th>
									<th scope="col">Name</th>
									<th scope="col">State</th>
									<th scope="col">Price</th>
								</tr>
							<thead>
							<tbody>
								{% for item in all_items %}
								<tr class="item-data">
									<td scope="row"></td>
									<td class="item-check-icon">
										<input class="form-check-input" type="checkbox" 
										value="" id="item-checkbox" name="item-check">
									</td>
									<td class="item-name" scope="row">{{ item.item_name }}</td>
									<td class="item-state" scope="row">{{ item.state }}</td>
									<td class="item-price" scope="row">{{ item.price }}</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
        		</div>
			<div class="col-md-6 text-center">
				<div class="row checkout-item-row">
						<div class="col-md-5" id="name-of-item">
							<div class="heading fw-bold fst-italic">
								Name
							</div>
						</div>
						<div class="col-md-2" id="quantity">
                                                        <div class="heading fw-bold fst-italic">
								Quantity
                                                        </div>
                                                </div>
						<div class="col-md-3" id="amount">
                                                        <div class="heading fw-bold fst-italic">
                                                                Amount
                                                        </div>
                                                </div>
						<div class="col-md-2" id="remove">
                                                        <div class="heading fw-bold fst-italic">
                                                                Remove
                                                        </div>
                                                </div>
                                </div>
				<div class="row submit-order">
					<div class="col-md-5" id="">
                                        	<h2>Total: Ksh<span class="" id="total-amount">0</span></h2>
                                        </div>
					<div class="col" id="">
                                                <div class="d-grid gap-2">
							<!-- Button trigger modal -->
  							<button class="btn btn-success btn-lg" type="button" id="pay-btn"
							data-bs-toggle="modal" data-bs-target="#order-modal">
								Pay
							</button>
						</div>
                                        </div>
				</div>
                	</div>
		</div>
	</div>
</div>

		<!-- Modal -->
		<div class="modal fade" id="order-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  			<div class="modal-dialog">
    				<div class="modal-content">
      					<div class="modal-header text-center">
        					<h5 class="modal-title text-center" id="exampleModalLabel">New Order</h5>
        					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      					</div>
      					<div class="modal-body">
						<form method="POST" action="{{ url_for('order_views.make_counter_order')  }}" id="new-order-form">
							  <p class="text-danger d-none" id="wrong-number">Wrong phone number</p>
							  <div class="form-group row pb-2">
							    <div class="d-flex justify-content-center pb-2 d-none" id="loadingSpinner">
  								<div class="spinner-border text-primary" role="status">
    									<span class="sr-only">Loading...</span>
  								</div>
							    </div>
							    <div class="d-none" id="orderMessage">
								    <p class="text-success"></p>
							    </div>
                                                            <label for="customer" class="col-sm-2 col-form-label">Customer:</label>
                                                            <div class="col-sm-10">
                                                              <input type="text" class="form-control" id="customer-phone-number">
                                                            </div>
                                                          </div>
							  <div class="form-group row">
							    <label for="counterNumber" class="col-sm-2 col-form-label">Counter:</label>
							    <div class="col-sm-10">
							      <input type="text" class="form-control" id="counterNumber" disabled>
							    </div>
							  </div>
							  <div class="form-group row">
                                                            <label for="tenderType" class="col-sm-2 col-form-label">Tender:</label>
                                                            <div class="col-sm-10">
                                                              <input type="text" class="form-control" id="tenderType" disabled>
                                                            </div>
                                                          </div>
							  <div class="form-group row">
							    <label for="waiterName" class="col-sm-2 col-form-label">Waiter:</label>
							    <div class="col-sm-10">
							      <input type="text" class="form-control" id="waiterName" disabled>
							    </div>
							  </div>
							  <div class="form-group row">
							    <label for="tableName" class="col-sm-2 col-form-label">Table:</label>
							    <div class="col-sm-10">
							      <input type="text" class="form-control" id="tableName" disabled>
							    </div>
							  </div>
							  <table class="table">
							    <thead>
							      <tr>
								<th scope="col">Item Name</th>
								<th scope="col">Quantity</th>
								<th scope="col">Amount</th>
							      </tr>
							    </thead>
							    <tbody id="order-item-details">


							    </tbody>
							  </table>
							  <div class="form-group row">
							    <label for="totalAmount" class="col-sm-2 col-form-label">Total:Ksh</label>
							    <div class="col-sm-10">
							      <input type="text" class="form-control text-center" id="totalAmount" disabled>
							    </div>
							  </div>
							  <div class="form-group row pt-3">
							      <button type="submit" class="btn btn-success btn-lg" id="final-pay">PAY</button>
							  </div>
							</form>
      					</div>
    				</div>
  			</div>
		</div>

{% endblock %}

views/order/templates/order.html
{% extends "base.html" %}

{% block content %}

<div class="pt-2">
	<div class="container py-2">
		<h2 class="text-center">Order Management</h2>
	</div>

	<div class="py-2" id="order_icons">
		<a class="btn btn-success" href="#" role="button">Orders</a>
		<a class="btn btn-success" href="{{ url_for('order_views.make_counter_order') }}" role="button">Counter</a>
		<a class="btn btn-success" href="{{ url_for('sales_views.make_credit_sale') }}" role="button">Credit Sale</a>
		<!-- Button trigger modal -->
		<button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#addNewCustomer">
			+Customer
		</button>
	</div>

	
	<div class="container py-2">
		<h2 class="text-center">Sale Invoices</h2>
		<hr>
	</div>

	<table class="table table-striped table-hover pt-3">
	<thead>
		<tr>
			<th scope="col"></th>
			<th scope="col">Date</th>
			<th scope="col">invoice no.</th>
			<th scope="col">Customer</th>
			<th scope="col">Narration</th>
			<th scope="col">Amount (Ksh)</th>
			<th scope="col">IsPaid</th>
			<th scope="col">Details</th>
		</tr>
	</thead>
	
	<tr>
		<th scope="col"></th>
		<th scope="col">
			<div class="input-group mb-3">
				<input type="date" class="form-control" aria-describedby="basic-addon1">
			</div>
		</th>
		<th scope="col">
			<div class="input-group mb-3">
				<input type="text" class="form-control" id="invoice_number_search" aria-describedby="basic-addon1">
			</div>	
		</th>
		<th scope="col">
			<div class="input-group mb-3">
				<input type="text" class="form-control" aria-describedby="basic-addon1">
			</div>
		</th>
		<th scope="col">
			<div class="input-group mb-3">
				<input type="text" class="form-control" aria-describedby="basic-addon1">
			</div>
		</th>
		<th scope="col">
			<div class="input-group mb-3">
				<input type="text" class="form-control" aria-describedby="basic-addon1">
			</div>
		</th>
		<th scope="col">
			<div class="input-group mb-3">
				<input type="text" class="form-control" aria-describedby="basic-addon1">
			</div>
		</th>
		<th scope="col"></th>
	</tr>

	<tbody>
		{% for invoice in invoices %}
		<tr>
			<th scope="row"></th>
			<td>{{ invoice.created_at.strftime('%d/%m/%Y') }}</td>
			<td class="inv_number">{{ invoice.transaction_number }}</td>
			<td>{{ invoice.customer_name }}</td>
			<td>{{ invoice.narration }}</td>
			<td>{{ invoice.amount }}</td>
			{% if invoice.isPaid == true %}
			<td><p class="text-success">Cleared</p></td>
			{% else %}
			<td><p class="text-danger">Pending</p></td>
			{% endif %}

			<td><button class="btn btn-primary invDetails btn-sm" type="button" data-bs-toggle="offcanvas"
					data-bs-target="#inv-details" aria-controls="offcanvasWithBothOptions">
					Details
				</button>
			</td>
		</tr>
		{% endfor %}
		<tr>
			<th scope="row"></th>
			<td scope="row"><b>Total = {{ number_of_invoices }}</b></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
	</table>

	<div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="inv-details" style="width: 50%;" 
		aria-labelledby="offcanvasWithBothOptionsLabel">
		<div class="offcanvas-header">
			<h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Invoice Items</h5>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
		<h1 class="" id="invNumberDisplay"></h1>
			<table class="table">
				<thead>
					<tr>
					<th scope="col">Item Name</th>
					<th scope="col">Quantity</th>
					<th scope="col">Amount</th>
					</tr>
				</thead>
				<tbody id="invItemDetails">
	

				</tbody>
            </table>
		 <div class="text-center">
		 	<button type="button" class="btn btn-success finishButtonClick">Tender</button>
		</div>
		</div>
	</div>
</div>

<!-- Modal Add Customer-->
<div class="modal fade" id="addNewCustomer" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Add a new Customer</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
				<form method="POST" action="" id="add_supplier_form">
					<div class="mb-3">
						<label for="supplier_name" class="form-label">Customer Name:</label>
						<input type="text" class="form-control" id="new_customer_name">
					</div>
					<div class="mb-3">
						<label for="contact" class="form-label">Contact:</label>
						<input type="text" class="form-control" id="contact">
					</div>
					<div class="mb-3">
						<label for="balance" class="form-label">Balance:</label>
						<input type="number" class="form-control" id="starting_balance" name="balance">
					</div>
					<div class="modal-footer">
						<button name="Btn" type="button" class="btn btn-primary" id="save_new_customer">Save</button>
					</div>
				</form>
				</div>
			</div>
	</div>
</div>

{% endblock %}