views/accounts/routes.py
#!/usr/bin/python3
"""Defines all the routes for the accounts view"""

from flask import Blueprint, render_template, request, flash, url_for, redirect, jsonify

from sqlalchemy.exc import IntegrityError

from datetime import datetime

from models.accounts_models.accounts_group import AccountGroup
from models.accounts_models.accounts import Account, Transaction
from models.purchases import Supplier
from models import storage

# defining the accounts_views blueprint
accounts_views = Blueprint('accounts_views', __name__,
                            template_folder='templates',
                            static_folder='static',
                            url_prefix='/accounts')


@accounts_views.route('/AccountMaster', strict_slashes=False)
def master_account():
    """Returns the Account mother template"""
    """
    group_name = "testGroup2"
        description = "test"
        nature_of_group = "asset"

        new_group_dict = {"group_name": group_name, "description": description, "nature_of_group": nature_of_group}

        new_group = LedgerGroup(**new_group_dict)
        account_storage.new(new_group)
        account_storage.save()

        print(new_group)
        return "SUccess..."
    """
    return render_template('accounts.html')

@accounts_views.route('/addNewAccount', methods=['POST',], strict_slashes=False)
def new_account(): #means new_account
    """Adds a new account to the database
    """
    if request.method == 'POST':
        account_details = request.get_json()

        # Call the function that sets the dr/cr values
        account_details = setting_dr_cr(account_details)

        # Creating the Account object
        account_object = Account(**account_details)

        # Saving the account to the database
        try:
            storage.new(account_object)
            storage.save()
            storage.close()
        except IntegrityError as e:
            return jsonify("Account name already exists in the system")
        except Exception as e:
            return jsonify("Unknown Exception occured")
        else:
            return jsonify("New account added successfully")

def setting_dr_cr(account_details):
    """
    Helper function to set the dr or cr value
    """
    if account_details["drcr"] == "dr":
        account_details["dr"] = account_details["account_opening_amount"]
        account_details["cr"] = 0
    else:
        account_details["cr"] = account_details["account_opening_amount"]
        account_details["dr"] = 0
    del account_details["drcr"]
    return account_details


@accounts_views.route('/last_payment_info', methods=['POST', 'GET'], strict_slashes=False)
def last_payment_info():
    """Get the details of last payment made"""
    if request.method == 'POST':
        supplier_and_account = request.get_json()

        # Get last payment
        storage.reload()
        last_payment = storage.get_last_payment(supplier_and_account["supplier"])
        balance = storage.get_supplier(supplier_and_account["supplier"]).balance

        if last_payment:
            # Return last payment details
            last_payment_details = {
                "date": last_payment.created_at.strftime("%d/%m/%Y"),
                "balance": balance
            }
            result = jsonify(last_payment_details)
            storage.save()
            storage.close()
            return result, 200
        else:
            last_payment_details = {
                    "date": 0,
                    "balance": 0
            }
            result = jsonify(last_payment_details)
            storage.save()
            storage.close()
            return result, 200
        

@accounts_views.route('/pay', methods=['POST', 'GET'], strict_slashes=False)
def payment():
    if request.method == 'POST':
        try:
            payment_details = request.get_json()
            payment_no = storage.generate_document_number("PAY")
            # Handle the transaction. Credit the paying account and debit the accounts payable
            storage.reload()
            paying_account = storage.get_account(payment_details["payingAccount"])
            payables_account = storage.get_account("Payables")

            transaction_details = {
                        "supplier": payment_details["supplier"],
                        "transaction_number": payment_no,
                        "amount": payment_details["amountPaid"],
                        "dr": payables_account.id,
                        "cr": paying_account.id,
                        }
            
            new_transaction = Transaction(**transaction_details)

            # append the accounts related to this transaction
            new_transaction.accounts.append(paying_account)
            new_transaction.accounts.append(payables_account)
            storage.new_modified(new_transaction)

            # update the supplier account balance
            supplier = storage.get_supplier(payment_details["supplier"])
            supplier.balance = supplier.balance - int(payment_details["amountPaid"])
            storage.new_modified(supplier)   
        except Exception as e:
            storage.rollback()
            storage.close()
            return jsonify({"error": f"Could not create a new payment. \n {e}"}), 500
        
        storage.save()
        storage.close()
        return jsonify(f"SUCCESS. \n Payment number {payment_no} created."), 200
    
    #payment_voucher_number = storage.generate_document_number('PAY')
    suppliers = storage.get_all_objects(Supplier)
    paying_accounts = storage.get_all_paying_accounts()

    return render_template('payment.html',
                           suppliers=suppliers,
                           paying_accounts=paying_accounts
                           )

views/accounts/templates/accounts.html
{% extends "base.html" %}

{% block content %}

<div class="pt-2">
	<div class="container py-2">
		<h2 class="text-center">Account Management</h2>
	</div>

	<div class="py-2">
		<!-- Button trigger modal Add Account -->
		<button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#addNewAccount">
  		Add Account
		</button>
		<!-- Modal Add Account-->
		<div class="modal fade" id="addNewAccount" tabindex="-1" aria-labelledby="addNewAccount" aria-hidden="true">
  			<div class="modal-dialog">
    				<div class="modal-content">
      					<div class="modal-header">
        					<h5 class="modal-title" id="exampleModalLabel">Create Account</h5>
        					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      					</div>
      					<div class="modal-body">
						<form method="POST" action="{{ url_for('accounts_views.new_account') }}" id="add_new_account">
							<div class="mb-3">
  								<label for="account_no" class="form-label">Account No.</label>
  								<input type="text" class="form-control" id="account_no" name="account_no" required>
							</div>
							<div class="mb-3">
									<label for="account_name" class="form-label">Account Name</label>
									<input type="text" class="form-control" id="account_name" name="account_name" required>
							</div>
							<div class="mb-3">
                                <label for="account_group" class="form-label">Account Group</label>
								<input class="form-control" list="datalistOptions" id="account_group" required>
								<datalist id="datalistOptions">
  									<option value="Accounts payable">
  									<option value="Accounts receivable">
  									<option value="Cash-in-hand">
									<option value="Bank account">
									<option value="Duties and taxes">
									<option value="Mobile money(MPESA)">
									<option value="Direct expenses">
									<option value="Fixed assets">
									<option value="Indirect expenses">
									<option value="Direct income">
									<option value="Indirect income">
									<option value="Loans and advances(Asset)">
									<option value="Loan(Liability)">
									<option value="Misc Expenses">
									<option value="Purchase accounts">
									<option value="Inventory">
								</datalist>
                            </div>
							<div class="input-group mb-3">
  								<input type="text" class="form-control" placeholder="Opening Amount" aria-label="opening_amount" id="opening_amount" required>
  								<span class="input-group-text">Dr/Cr</span>
								<input class="form-control" list="dr_cr_options" id="dr_cr" required>
									<datalist id="dr_cr_options">
											<option value="dr">
											<option value="cr">
									</datalist>

							</div>

							<div class="modal-footer">
								<button name="Btn" type="button submit" value="Submit" id="newAccountForm" class="btn btn-primary">Save</button>
							</div>
						</form>
      					</div>
    				</div>
  			</div>
		</div>
	</div>
</div>
{% endblock %}

views/accounts/templates/payment.html
{% extends "base.html" %}

{% block content %}

<!-- Add payment form-->
<div class="container" data-bs-scroll="true" tabindex="-1" id="payment_form" style="height: 95vh;">
<div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">New Payment</h5>
    
</div>
<div class="offcanvas-body">
<form method="POST" action="" id="">
    <div class=" input-group mb-3">
                        <input type="text" class="form-control" placeholder="Voucher No.(SystemGen)" id="payment_no" disabled>
                        <span class="input-group-text">Voucher Date</span>
                        <input class="form-control" type="date" id="supplierInvDate" required>
                </div>
    <div class="input-group mb-3">
        <input class="form-control" list="supplierList" id="nameOfSupplier" placeholder="Supplier" required>
        <datalist id="supplierList">
            {% for supplier in suppliers %}
                <option value="{{ supplier.supplier_name }}">
            {% endfor %}
        </datalist>
        <span class="input-group-text">Party Account(cr)</span>
        <input class="form-control" list="accountList" id="fromAccount" placeholder="Account" required>
        <datalist id="accountList">
            {% for paying_account in paying_accounts %}
                <option value="{{ paying_account.account_name }}">
            {% endfor %}
        </datalist>
    </div>
    <div class=" input-group mb-5">
        <span class="input-group-text">Narration:</span>
        <input class="form-control" type="text" id="payNarration" required>
    </div>
    <div class=" input-group mb-4">
        <button class="btn btn-outline-success" type="button" id="getOutstandingBalance">Load</button>
    </div>

    <!-- Table for item details -->
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Last Payment</th>
                <th scope="col">Balance</th>
                <th scope="col">Amount(Ksh)</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody id="paymentDetails">
            <tr>
                <td scope="col">
                    <input class="form-control" type="text" id="lastPaymentDate" disabled>
                </td>
                <td scope="col">
                    <input class="form-control" type="text" id="currentBalance" disabled>
                </td>
                <td scope="col">
                    <input class="form-control" type="text" id="amountPaid" required>
                </td>
                <td scope="col"></td>
            </tr>
        </tbody>
    </table>
    <!-- End of table for invoice item details -->
    <div class="row justify-content-center text-end pt-5">
        <div class="col-sm-6 col-md-8 d-grid gap-2">
            <button type="button" class="btn btn-lg btn-success" id="paymentSaveBtn">Save</button>
        </div>
    </div>
</form>
</div>

{% endblock content %}