views/table/routes.py
#!/usr/bin/python3
"""Defines all the routes for the waiter view"""

from flask import Blueprint, render_template, request, flash, url_for, redirect

# models imports
from models.tables import Table

# python imports
from datetime import datetime
import uuid
import os

# sqlalchemy imports
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, scoped_session
from sqlalchemy import String, Column, Integer
from sqlalchemy.orm import relationship


# base_model imports
from models.base_model import BaseModel, Base, time
from models import storage

# model imports
from models.tables import Table

# engine imports
from engine.db_storage import classes, DBStorage

# define table_views blueprint
table_views = Blueprint('table_views', __name__,
                            template_folder='templates',
                            static_folder='static',
                            url_prefix='/table')

@table_views.route('/all-tables', methods=['GET','POST'], strict_slashes=False)
def get_all_tables():
    """returns all the tables in the system
    """
    all_tables = storage.get_all_tables()
    print(all_tables)
    number_of_tables = len(all_tables)
    return render_template('table.html', all_tables=all_tables, number_of_tables=number_of_tables)

@table_views.route('/add-table', methods=['GET', 'POST'], strict_slashes=False)
def add_table():
    """Adds a new table to the database
    """
    if request.method == 'POST':
        table_name = request.form.get('table_name')
        capacity = request.form.get('capacity')
        location = request.form.get('location')

        table = storage.check_table_if_exists(table_name)
        if table:
            flash('Table with the name {} already exists'.format(table.table_name))
            return redirect(url_for('table_views.get_all_tables'))
        else:
            table_details = {"table_name":table_name, "capacity":capacity, "location":location}
            table_obj = Table(**table_details)
            storage.new(table_obj)
            storage.save()

            flash('Table added successfuly...')
            return redirect(url_for('table_views.get_all_tables'))

    else:
        return render_template('new_table.html')

views/table/templates/table.html
{% extends "base.html" %}

{% block content %}

<div class="pt-2">
	<div class="container py-2">
		<h2 class="text-center">Table Management</h2>
	</div>

	<div class="py-2">
		<!-- Button trigger modal -->
		<button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
  		Add table
		</button>
		<!-- Modal -->
		<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  			<div class="modal-dialog">
    				<div class="modal-content">
      					<div class="modal-header">
        					<h5 class="modal-title" id="exampleModalLabel">Add a new table</h5>
        					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      					</div>
      					<div class="modal-body">
						<form method="POST" action="{{ url_for('table_views.add_table') }}" id="add_table_form">
							<div class="mb-3">
  								<label for="table_name" class="form-label">Table Name</label>
  								<input type="text" class="form-control" id="table_name" name="table_name">
							</div>
							<div class="mb-3">
                                                                <label for="capacity" class="form-label">Capacity</label>
                                                                <input type="number" class="form-control" id="capacity" name="capacity">
                                                        </div>
							<div class="mb-3">
                                                                <label for="location" class="form-label">Location</label>
                                                                <input type="text" class="form-control" id="location" name="location">
                                                        </div>
							<div class="modal-footer">
								<button onclick="form_submit()" name="Btn" type="button" 
									class="btn btn-primary">Save</button>
							</div>
						</form>
      					</div>
    				</div>
  			</div>
		</div>
	</div>

	{% with messages = get_flashed_messages() %}
	    {% if messages %}
	    	<div class="success">
			{{ messages[0] }}
		</div>
	    {% endif %}
	{% endwith %}

	<table class="table table-dark">
	<thead>
		<tr>
		<th scope="col"></th>
		<th scope="col">Table Name</th>
      		<th scope="col">Location</th>
      		<th scope="col">Capacity</th>
    		</tr>
	</thead>
	<tbody>
		{% for table in all_tables %}
		<tr>
			<th scope="row"></th>
			<td>{{table.table_name}}</td>
      			<td>{{table.location}}</td>
			<td>{{table.capacity}}</td>
		</tr>
		{% endfor %}
		<tr>
			<th scope="row"></th>
			<td scope="row"><b>Total = {{ number_of_tables }}</b></td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
 
	</table>
</div>

{% endblock %}